export default {
    typescript: true,
    menu: [
        "Welcome",
        "Technology We Use",
        "Installation",
        "Overview",
        "Non Monorepo Structure",
        "Monorepo Packages Structure",
        "Getting Started",
        "AsyncComponent",
        {
            name: "Components",
            menu: [
                "Shop (Algolia)",
                "Authentication",
                "UI Elements",
                "Widgets",
            ],
        },
        "Available Scripts",
        "Development",
        "Technologies",
        "Project Structure",
        "Customization",
        "Layouts",
        "Styles and Assets",
        "Utilities",
        "Internationalization",
        {
            name: "Back-End Integration",
            menu: ["API integration", "Data Fetching"],
        },
        "Deployment",
        { name: "SEO and Analytics", menu: ["SEO", "Analytics"] },
        { name: "Components", menu: ["Alert", "Button"] },
        "Resources",
        "FAQ",
        "Support",
        "Versions",
    ],
};
