export default {
    typescript: true,
    menu: [
        "Welcome",
        "Technology We Use",
        "Pre Installation",
        "Installation",
        "Architecture Overview",
        "Non Monorepo Structure",
        "Monorepo Packages Structure",
        {name: "Getting Started", menu: ["Authentication"]},
        "Customization",
        "AsyncComponent",
        {
            name: "Components",
            menu: [
                "Shop (Algolia)",
                "Authentication",
                "UI Elements",
                "Widgets",
                "Map",
                "Leaflet Map",
                "Isotope",
                "Page Components",
                "Sidebar & Routing",
                "Form Elements",
                "Contact",
                "Calendar",
                "Ant Table",
                "React Trend Chart",
                "Recharts",
                "ReactVis Charts",
                "React-Chart-2",
                "Uppy",
                "Chat Firebase",
            ],
        },
        "RTL CSS Transformation",
        "Multi Language Support",
        "Express JWT Implementation",
        // "Deployment",
        "Spark JWT Implementation",
        "Flask JWT",
        "Django JWT",
        // { name: "Deployment", menu: ["AWS"] },
        "FAQ",
    ],
};
