export default {
    typescript: true,
    menu: [
        "Welcome",
        "Technology We Use",
        "Installation",
        "Overview",
        "Non Monorepo Structure",
        "Monorepo Packages Structure",
        "Getting Started",
        "AsyncComponent",
        {
            name: "Components",
            menu: [
                "Shop (Algolia)",
                "Authentication",
                "UI Elements",
                "Widgets",
                "Map",
                "Leaflet Map",
                "Isotope",
                "Page Components",
                "Sidebar & Routing",
                "Form Elements",
                "Contact",
                "Calendar",
                "Ant Table",
                "React Trend Chart",
                "Recharts",
                "ReactVis Charts",
                "React-Chart-2",
                "Uppy",
                "Chat Firebase",
            ],
        },
        "RTL CSS Transformation",
        "Multi Language Support",
        "Express JWT Implementation",
        "Deployment",
        "Spark JWT Implementation",
        "Flask JWT",
        "Django JWT",
        "FAQ",

        "Available Scripts",
        "Development",
        "Technologies",
        "Project Structure",
        "Customization",
        "Layouts",
        "Styles and Assets",
        "Utilities",
        "Internationalization",
        {
            name: "Back-End Integration",
            menu: ["API integration", "Data Fetching"],
        },
        { name: "SEO and Analytics", menu: ["SEO", "Analytics"] },
        { name: "Components", menu: ["Alert", "Button"] },
        "Resources",

        "Support",
        "Versions",
    ],
};
